# Generated by Django 3.2.8 on 2021-10-31 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='user_name',
            new_name='username',
        ),
    ]
